baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'gohost'

[params.style]
color = 'blue'

[security.http]
mediaTypes = ['^font/woff2$']

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false